# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llmtools',
                'doc_host': 'https://franfram.github.io',
                'git_url': 'https://github.com/franfram/llmtools',
                'lib_path': 'llmtools'},
  'syms': {'llmtools.core': {'llmtools.core.foo': ('core.html#foo', 'llmtools/core.py')}}}
