# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['hello_llm', 'ingests_documents', 'query_llm']

# %% ../nbs/00_core.ipynb 3
def hello_llm(): 
    "The LLM talks to you"
    print('LLM: Hello Human World!')

# %% ../nbs/00_core.ipynb 4
def ingests_documents(): 
    "ingests documents"
    print('LLM: yumyum!')

# %% ../nbs/00_core.ipynb 5
def query_llm():
    "Queries the LLM"
    print("LLM: Hold on a sec")
